#!/usr/bin/env bash
#
# Generate Python client bindings for the Cypher GridPay smart contracts.
#
# Produces one importable package per contract under bindings/python/<contract>/,
# suitable for Django / FastAPI / Celery backends. Each package is generated by
# `stellar contract bindings python` and is type-annotated by the CLI, so the
# resulting SDK is type-safe and checkable with mypy / pyright.
#
# Usage:
#   ./scripts/generate-python-bindings.sh              # build wasm, then generate
#   ./scripts/generate-python-bindings.sh --no-build   # reuse existing wasm
#
# Requirements:
#   - stellar CLI (provides `stellar contract build` and `stellar contract bindings`)
#   - bash 4+
#
# See docs/PYTHON_SDK.md for usage.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_ROOT="${REPO_ROOT}/bindings/python"

BUILD=1
for arg in "$@"; do
  case "$arg" in
    --no-build) BUILD=0 ;;
    -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

if ! command -v stellar >/dev/null 2>&1; then
  echo "error: 'stellar' CLI not found in PATH." >&2
  echo "       install: cargo install --locked stellar-cli --features opt" >&2
  exit 1
fi

# contract-crate-dir : contract-name : expected wasm artifact name
# Crate names come from each contract's Cargo.toml [package] name.
CONTRACTS=(
  "core/contracts/payment:payments"
  "core/contracts/escrow:escrow"
  "core/contracts/refund:refund"
  "orchestrator/contracts/admin:admin"
)

# `stellar contract build` emits wasm32v1-none artifacts under each workspace's
# target dir. The admin contract lives in the orchestrator workspace; the other
# three live in core.
wasm_dir_for() {
  case "$1" in
    orchestrator/*) printf '%s' "${REPO_ROOT}/orchestrator/target/wasm32v1-none/release" ;;
    *)               printf '%s' "${REPO_ROOT}/core/target/wasm32v1-none/release" ;;
  esac
}

if [[ "$BUILD" -eq 1 ]]; then
  echo "==> Building contracts to WASM"
  make -C "${REPO_ROOT}" build
fi

mkdir -p "${OUT_ROOT}"

fail=0
for entry in "${CONTRACTS[@]}"; do
  dir="${entry%%:*}"
  name="${entry##*:}"
  wasm_dir="$(wasm_dir_for "$dir")"
  wasm="${wasm_dir}/${name}.wasm"

  if [[ ! -f "$wasm" ]]; then
    echo "error: expected artifact not found: $wasm" >&2
    echo "       run without --no-build, or check the contract's package name." >&2
    fail=1
    continue
  fi

  out="${OUT_ROOT}/${name}"
  echo "==> Generating Python bindings for '${name}' -> bindings/python/${name}"
  rm -rf "$out"
  mkdir -p "$out"
  stellar contract bindings python \
    --wasm "$wasm" \
    --output-dir "$out" \
    --class-name "${name^}Client"
done

if [[ "$fail" -ne 0 ]]; then
  echo >&2
  echo "one or more contracts failed to generate; see errors above." >&2
  exit 1
fi

cat <<EOF

==> Done. Generated packages:

$(cd "${OUT_ROOT}" && ls -1 2>/dev/null | sed 's/^/    bindings\/python\//')

Next steps:
    pip install -e bindings/python/payments      # or install from your app's requirements
    python examples/python/quickstart.py
EOF
