#!/usr/bin/env bash
#
# Generate the TypeScript client SDK for the Cypher GridPay smart contracts.
#
# Produces the NPM-ready package @cypher-gridpay/contracts-sdk under
# sdk/typescript/. Every contract is compiled to a `stellar contract bindings
# typescript` module and re-exported from a single typed entrypoint, so an app
# does:
#
#     import { PaymentsClient } from "@cypher-gridpay/contracts-sdk";
#
# Usage:
#   ./scripts/generate-ts-bindings.sh              # build wasm, then generate
#   ./scripts/generate-ts-bindings.sh --no-build   # reuse existing wasm
#   ./scripts/generate-ts-bindings.sh --install    # also run npm install + build
#
# Requirements:
#   - stellar CLI
#   - node 18+ and npm (only for --install)
#
# See sdk/typescript/README.md and the root README.md.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SDK_DIR="${REPO_ROOT}/sdk/typescript"
GEN_DIR="${SDK_DIR}/src/generated"

BUILD=1
INSTALL=0
for arg in "$@"; do
  case "$arg" in
    --no-build) BUILD=0 ;;
    --install)  INSTALL=1 ;;
    -h|--help)  sed -n '2,24p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

if ! command -v stellar >/dev/null 2>&1; then
  echo "error: 'stellar' CLI not found in PATH." >&2
  echo "       install: cargo install --locked stellar-cli --features opt" >&2
  exit 1
fi

# contract-crate-dir : contract-name
# Crate names come from each contract's Cargo.toml [package] name.
CONTRACTS=(
  "core/contracts/payment:payments"
  "core/contracts/escrow:escrow"
  "core/contracts/refund:refund"
  "orchestrator/contracts/admin:admin"
)

wasm_dir_for() {
  case "$1" in
    orchestrator/*) printf '%s' "${REPO_ROOT}/orchestrator/target/wasm32v1-none/release" ;;
    *)               printf '%s' "${REPO_ROOT}/core/target/wasm32v1-none/release" ;;
  esac
}

if [[ "$BUILD" -eq 1 ]]; then
  echo "==> Building contracts to WASM"
  make -C "${REPO_ROOT}" build
fi

rm -rf "${GEN_DIR}"
mkdir -p "${GEN_DIR}"

fail=0
generated=()
for entry in "${CONTRACTS[@]}"; do
  dir="${entry%%:*}"
  name="${entry##*:}"
  wasm="$(wasm_dir_for "$dir")/${name}.wasm"

  if [[ ! -f "$wasm" ]]; then
    echo "error: expected artifact not found: $wasm" >&2
    echo "       run without --no-build, or check the contract's package name." >&2
    fail=1
    continue
  fi

  out="${GEN_DIR}/${name}"
  echo "==> Generating TypeScript bindings for '${name}'"
  mkdir -p "$out"
  stellar contract bindings typescript \
    --wasm "$wasm" \
    --output-dir "$out" \
    --class-name "${name^}Client"
  generated+=("$name")
done

if [[ "$fail" -ne 0 ]]; then
  echo >&2
  echo "one or more contracts failed to generate; see errors above." >&2
  exit 1
fi

# Regenerate the barrel so it can never drift from the contract set.
{
  echo "// AUTO-GENERATED by scripts/generate-ts-bindings.sh - do not edit by hand."
  echo "// Regenerate with: ./scripts/generate-ts-bindings.sh"
  echo
  for n in "${generated[@]}"; do
    echo "export * as ${n^} from './${n}/index.js';"
  done
} > "${GEN_DIR}/index.ts"

# Keep tsconfig output aligned with the barrel target.
if [[ "$INSTALL" -eq 1 ]]; then
  command -v npm >/dev/null 2>&1 || { echo "error: npm not found in PATH." >&2; exit 1; }
  echo "==> npm install"
  (cd "${SDK_DIR}" && npm install)
  echo "==> npm run build"
  (cd "${SDK_DIR}" && npm run build)
fi

cat <<EOF

==> Done. Generated:

$(printf '    sdk/typescript/src/generated/%s\n' "${generated[@]}")
    sdk/typescript/src/generated/index.ts   (barrel, regenerated each run)

Next steps:
    cd sdk/typescript
    npm install
    npm run build
    npm pack        # produces @cypher-gridpay-contracts-sdk-<version>.tgz
EOF
