#!/usr/bin/env bash
# generate-python-bindings.sh — Generate Python client SDK for Cypher GridPay contracts
set -euo pipefail

OUTPUT_DIR="${1:-python-sdk}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

command -v stellar >/dev/null 2>&1 || { log_error "Stellar CLI not found."; exit 1; }
command -v python3 >/dev/null 2>&1 || { log_error "python3 not found."; exit 1; }

CONTRACTS=("payment" "escrow" "refund" "admin")
CONTRACT_WASM_PATHS=(
    "core/target/wasm32v1-none/release/payment.wasm"
    "core/target/wasm32v1-none/release/escrow.wasm"
    "core/target/wasm32v1-none/release/refund.wasm"
    "orchestrator/target/wasm32v1-none/release/admin.wasm"
)

log_info "Generating Python bindings for Cypher GridPay contracts..."
log_info "Output directory: ${OUTPUT_DIR}"

mkdir -p "${OUTPUT_DIR}"

for i in "${!CONTRACTS[@]}"; do
    contract_name="${CONTRACTS[$i]}"
    wasm_path="${REPO_ROOT}/${CONTRACT_WASM_PATHS[$i]}"

    if [[ ! -f "${wasm_path}" ]]; then
        log_warn "WASM not found for ${contract_name}: ${wasm_path}"
        continue
    fi

    log_info "Generating Python bindings for ${contract_name}..."
    stellar contract bindings python \
        --wasm "${wasm_path}" \
        --output "${OUTPUT_DIR}/${contract_name}" \
        2>&1 || log_warn "Bindings generation failed for ${contract_name}"
done

log_info "Creating Python package structure..."

cat > "${OUTPUT_DIR}/__init__.py" << 'PYEOF'
"""
Cypher GridPay Python SDK

Auto-generated Python client bindings for Cypher GridPay smart contracts.
Generated by scripts/generate-python-bindings.sh
"""

from .payment import PaymentContract
from .escrow import EscrowContract
from .refund import RefundContract
from .admin import AdminContract

__all__ = [
    "PaymentContract",
    "EscrowContract",
    "RefundContract",
    "AdminContract",
]
PYEOF

cat > "${OUTPUT_DIR}/setup.py" << 'PYEOF'
from setuptools import setup, find_packages

setup(
    name="cypher-gridpay-sdk",
    version="0.1.0",
    description="Python SDK for Cypher GridPay smart contracts",
    author="Cypher GridPay",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "stellar-sdk>=10.0.0",
    ],
)
PYEOF

cat > "${OUTPUT_DIR}/README.md" << 'MDEOF'
# Cypher GridPay Python SDK

Auto-generated Python client bindings for Cypher GridPay smart contracts.

## Installation

```bash
pip install -e .
```

## Quickstart

```python
from cypher_gridpay_sdk import PaymentContract, EscrowContract

payment = PaymentContract(
    contract_id="C...",
    rpc_url="https://soroban-testnet.stellar.org",
    network_passphrase="Test SDF Network ; September 2015",
)

payment_info = payment.get_payment(payment_id=1)
```
MDEOF

log_info "Python SDK generated successfully in ${OUTPUT_DIR}/"
