#!/usr/bin/env bash
# generate-ts-bindings.sh — Generate TypeScript client SDK for Cypher GridPay contracts
# This script uses Stellar CLI to generate TypeScript bindings for all four contracts.
# Prerequisites: stellar CLI, node, npm
# Usage: ./scripts/generate-ts-bindings.sh [output_dir]

set -euo pipefail

OUTPUT_DIR="${1:-ts-sdk}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

command -v stellar >/dev/null 2>&1 || { log_error "Stellar CLI not found. Install: cargo install --locked stellar-cli --features opt"; exit 1; }
command -v node >/dev/null 2>&1 || { log_error "node not found"; exit 1; }
command -v npm >/dev/null 2>&1 || { log_error "npm not found"; exit 1; }

CONTRACTS=("payment" "escrow" "refund" "admin")
CONTRACT_WASM_PATHS=(
    "core/target/wasm32v1-none/release/payment.wasm"
    "core/target/wasm32v1-none/release/escrow.wasm"
    "core/target/wasm32v1-none/release/refund.wasm"
    "orchestrator/target/wasm32v1-none/release/admin.wasm"
)

log_info "Generating TypeScript bindings for Cypher GridPay contracts..."
log_info "Output directory: ${OUTPUT_DIR}"

mkdir -p "${OUTPUT_DIR}"

for i in "${!CONTRACTS[@]}"; do
    contract_name="${CONTRACTS[$i]}"
    wasm_path="${REPO_ROOT}/${CONTRACT_WASM_PATHS[$i]}"

    if [[ ! -f "${wasm_path}" ]]; then
        log_warn "WASM not found for ${contract_name}: ${wasm_path}"
        log_warn "Skipping ${contract_name} — run 'make build' first"
        continue
    fi

    log_info "Generating TypeScript bindings for ${contract_name}..."
    stellar contract bindings typescript \
        --wasm "${wasm_path}" \
        --output "${OUTPUT_DIR}/${contract_name}" \
        2>&1 || log_warn "Bindings generation failed for ${contract_name}"
done

log_info "Creating NPM package structure..."

cat > "${OUTPUT_DIR}/package.json" << 'PKGEOF'
{
  "name": "@cypher-gridpay/contracts-sdk",
  "version": "0.1.0",
  "description": "TypeScript SDK for Cypher GridPay smart contracts",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc",
    "test": "jest"
  },
  "keywords": ["stellar", "soroban", "cypher-gridpay", "smart-contracts"],
  "author": "Cypher GridPay",
  "license": "MIT",
  "dependencies": {
    "@stellar/stellar-sdk": "^12.0.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.0.0"
  }
}
PKGEOF

cat > "${OUTPUT_DIR}/tsconfig.json" << 'TSEOF'
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
TSEOF

cat > "${OUTPUT_DIR}/src/index.ts" << 'TSEOF'
/**
 * Cypher GridPay TypeScript SDK
 *
 * Auto-generated TypeScript client bindings for Cypher GridPay smart contracts.
 * Generated by scripts/generate-ts-bindings.sh
 */

export { PaymentContract } from './payment';
export { EscrowContract } from './escrow';
export { RefundContract } from './refund';
export { AdminContract } from './admin';
TSEOF

cat > "${OUTPUT_DIR}/README.md" << 'MDEOF'
# @cypher-gridpay/contracts-sdk

TypeScript SDK for Cypher GridPay smart contracts.

## Installation

```bash
npm install @cypher-gridpay/contracts-sdk
```

## Quickstart

```typescript
import { PaymentContract, EscrowContract } from '@cypher-gridpay/contracts-sdk';

const payment = new PaymentContract({
  contractId: 'C...',
  rpcUrl: 'https://soroban-testnet.stellar.org',
  networkPassphrase: 'Test SDF Network ; September 2015',
});

// Query payment details
const info = await payment.getPayment({ paymentId: 1n });

// Create a payment
const paymentId = await payment.createPayment({
  customer: 'GABC...',
  merchant: 'GDEF...',
  amount: 10000n,
  token: 'CXYZ...',
  currency: 'USDC',
  expirationDuration: 0n,
  metadata: 'Order #12345',
});
```

## Contracts

- **PaymentContract** — Payment creation, completion, refunds, and fee management
- **EscrowContract** — Fund holding, dispute resolution, and clawback
- **RefundContract** — Refund processing and arbitration
- **AdminContract** — Administrative control and pause/unpause
MDEOF

log_info "TypeScript SDK generated successfully in ${OUTPUT_DIR}/"
log_info "To build: cd ${OUTPUT_DIR} && npm install && npm run build"
